spring.application.name=gerenciamento-estoque
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/estoquesenai_db
spring.datasource.username=postgres
spring.datasource.password=postgres