spring.application.name=escola_xyz
# Configurações do banco de dados
spring.jpa.database = postgresql
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Informações para conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/db_escola_xyz
spring.datasource.username=postgres
spring.datasource.password=postgres
